### ISSUE TITLE
erro na compilação em linux

### ISSUE THREAD

**Issue by fabricix** [bismarckjunior/TemplatePUC#1]
Ao compilar o `/Tese_modelo/Thesis.tex` em linux tenho a seguinte mensagem de erro

`/usr/share/texlive/texmf-dist/tex/latex/biblatex/biblatex_.sty:11467: Package biblatex Error: Style 'abnt' not found. [\RequireBibliographyStyle{\blx@bbxfile}]`

**Comment by bismarckjunior** [comment]
@fabricix, verifique se o biblatex está instalado corretamente. Dê uma olhada neste link: https://github.com/abntex/biblatex-abnt.

**Comment by fabricix** [comment]
@bismarckjunior conforme [1] `O biblatex-abnt está incluso no TeX Live a partir de 2016`. A versão que eu tenho é `texlive is the newest version (2015.20160320-1ubuntu0.1)` e pode ser devido a isso. Para mim não fica claro se a instalação manual mencionada [2] deve manter a estrutura dos diretórios ao copiar os arquivos ou não.

Foram copiados os arquivos mencionados em [1] para a pasta `/usr/share/texlive/texmf-dist/tex/latex/biblatex-contrib/biblatex-abnt` e logo executado o comando `texhash` e tenho o seguinte erro `/usr/share/texlive/texmf-dist/tex/latex/biblatex/biblatex_.sty:11467: Package biblatex Error: Style 'abnt' not found`.

[1] https://github.com/abntex/biblatex-abnt
[2] https://github.com/abntex/biblatex-abnt#instala%C3%A7%C3%A3o

**Comment by bismarckjunior** [comment]
@fabricix, acredito que mater ou não a estrutura dos diretórios seja opcional já que o texhash fará a varredura. Porém, eu manteria a estrutura de pastas (diferente do que sugere o autor). 

Eu não lembro de ter encontrado esses problemas na minha instalação do linux. Acredito ter utilizado o TeXLive 2016, mas não tenho certeza. Sugiro atualizar o TexLive para uma versão mais recente, pois já vem com o BibLateX instalado (e possivelmente o abnt também).

**Comment by fabricix** [comment]
@bismarckjunior foram copiados os arquivos diretamente na pasta e o problema continua. 
Tal vez deva-se especificar de forma explícita os requerimentos de linux (e do entorno em geral) no qual https://github.com/bismarckjunior/TemplatePUC funciona e é testado (veja isso como exemplo https://github.com/processing/processing/wiki/Build-Instructions).
